version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata: /var/lib/postgresql/data

volumes:
  pgdata: {}